# extend keys (make shift available)
set-option -g extended-keys on
# make colors normal
set-option -g default-terminal "xterm-256color"
# make the keyboard NORMAL
#set-window-option -g xterm-keys on
# change the prefix from ctrl+b to ctrl+f
unbind C-b
set-option -g prefix C-f
bind C-f send-prefix
bind -n C-f send-prefix
# split panes with ctrl+o and ctrl+e
unbind e
unbind o
unbind %
bind -n C-e split-window -h -c "#{pane_current_path}" # split window in the current directory
unbind '"'
bind -n C-o split-window -v -c "#{pane_current_path}" # split window in the current directory
# enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
# switch panes using alt+arrows without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# search & select sessions
unbind s
bind -n M-s choose-session
# detach client
bind -n M-d detach-client
