# extend keys (make shift available)
set-option -g extended-keys on
# make colors normal
set-option -g default-terminal "xterm-256color"
# make the keyboard NORMAL
#set-window-option -g xterm-keys on
# change the prefix from ctrl+b to ctrl+f
unbind C-b
set-option -g prefix C-f
bind C-f send-prefix
bind -n C-f send-prefix
# split panes with ctrl+o and ctrl+e
unbind e
unbind o
unbind %
bind -n C-e split-window -h -c "#{pane_current_path}" # split window in the current directory
unbind '"'
bind -n C-o split-window -v -c "#{pane_current_path}" # split window in the current directory
# enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
# switch panes using alt+arrows without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# search & select sessions
unbind s
bind -n M-s choose-session
# detach client
bind -n M-d detach-client
# status bar
set-window-option -g status-left " #H - #S "
# new session - current path
bind -n M-n new-session -c "#{pane_current_path}"
# display session on bottom bar
set -g status-right-length 80
set -g status-right '[#(tmux ls -F "##S##{?session_attached,*,}" | tr "\n" " " | sed "s/ $    //" )]'
# switch sessions with prefix + arrows
bind -n M-PageDown switch-client -n
bind -n M-PageUp switch-client -p
# reload configuration on the fly
bind r source-file ~/.tmux.conf
